### ISSUE TITLE
Workflow genera conflictos por el script en forks no actualizados

### ISSUE THREAD

**Issue by SrVariable** [mouredev/roadmap-retos-programacion#1077]
# Descripción

El script `stats.py` genera conflictos si un fork no está al día. Esto se debe a que cuando se ejecuta el workflow `stats.yml` los datos que obtiene `stats.py` para generar el archivo `stats.json` provienen del repositorio actual y no del original.

Si el repositorio al hacer el fork tiene 10 archivos y luego se aceptan 5 PR, el repositorio original pasará a tener 15 archivos mientras que el fork seguirá con los 10. 

# Propuesta

- Una posible solución podría ser modificar el script `stats.py` para que obtenga los datos del repositorio original directamente.
- Otra posible solución podría ser modificar el workflow `stats.yml` para que haga un pull del repositorio original. De esta manera el script `stats.py` obtendría los datos actualizados (Esto seguiría generando conflictos, pero reduciría considerablemente la cantidad).

**Comment by mouredev** [comment]
¡Hola!

He realizado una modificación en la Action para que sólo se ejecute en el repositorio original. Debería ser suficiente para solucionar el problema.
