### ISSUE TITLE
archivo fuera de la carpeta correcta

### ISSUE THREAD

**Issue by SaezMD** [mouredev/roadmap-retos-programacion#2212]
En el ejercicio 9, carpeta PYTHON hay un archivo con extensión: .java.
¿Lo podéis colocar en la carpeta correcta?

![error java](https://github.com/mouredev/roadmap-retos-programacion/assets/94844441/1d101522-c226-4843-8c80-fff7a65bb418)

Gracias.

**Comment by sperezsa** [comment]
Hola, parece que ha ocurrido en la PR 2183. #09 - Python

**Comment by hozlucas28** [comment]
Ya lo han solucionado, [09- Herencia](https://github.com/mouredev/roadmap-retos-programacion/tree/main/Roadmap/09%20-%20HERENCIA/python).

**Comment by SaezMD** [comment]
Solucionado.

Gracias.
