### ISSUE TITLE
Los retos estan al revés?

### ISSUE THREAD

**Issue by darkyelox** [mouredev/roadmap-retos-programacion#4867]
Primero que todo gran pagina de retos y ejercicions, los estoy haciendo con Rust, segundo queria saber si los retos están al revés, parece que empezamos desde el  #29 hasta el #0, es esto incencional?

![image](https://github.com/mouredev/roadmap-retos-programacion/assets/8183191/677e0a2d-f9b4-4ef7-8b6a-56ce8e568757)

Los ids de los retos parecen estar al derecho, me gustaria poder enlazar cada reto con el id en mi código usando un anchor, tal como https://retosdeprogramacion.com/roadmap/#16 pero en este caso estaria apuntando al reto equivocado.

Si es un bug, puedo tratar de solucionarlo.

PD: sería bueno tener el sitio en inglés también.

**Comment by EmmanuelMMontesinos** [comment]
Entiendo que es por ser el reto actual (osea, el que toca esta semana)

**Comment by NahuelBorromeo** [comment]
Entiendo que es para que aparezca el último arriba, ya que semanalmente se resuelve en stream.

**Comment by darkyelox** [comment]
Entiendo, si ese es el caso, pueden cerrar mi tarea.

**Comment by sarismejiasanchez** [comment]
Los retos estan ordenados de manera descendente, el primer reto que aparece es el que corresponde a la semana actual.
