### ISSUE TITLE
Correr código

### ISSUE THREAD

**Issue by Noelete** [mouredev/roadmap-retos-programacion#5281]
No encuentro la manera de hacer correr el código. No me aparece el botón de Play. Perdón, estoy muuuuuy verde

**Comment by EmmanuelMMontesinos** [comment]
> No encuentro la manera de hacer correr el código. No me aparece el botón de Play. Perdón, estoy muuuuuy verde

Para ver las stats dices? :
Roadmap/stats.py

Pero si lo preguntas pensando que este repositorio es un programa no es así.

Son retos semanales que hace Brais Moure para su comunidad (Para mejorar entre todos nuestras capacidades, cada uno en el lenguaje que elija)

Espero ser de ayuda

**Comment by ANTDORVEN** [comment]
Hola buenas a todos¡¡¡¡¡
Estoy empezando en esto y estoy algo verde, he realizado el primer ejercicio pero lo tengo guardado en mi pc, estoy intentando 
pasarlo a la plataforma de Git o Github (que me enredo un poco)  y no me deja sincronizarlo, podeis ayudarme????

**Comment by EmmanuelMMontesinos** [comment]
> Hola buenas a todos¡¡¡¡¡ Estoy empezando en esto y estoy algo verde, he realizado el primer ejercicio pero lo tengo guardado en mi pc, estoy intentando pasarlo a la plataforma de Git o Github (que me enredo un poco) y no me deja sincronizarlo, podeis ayudarme????

Aquí tienes el curso de Brais para Git y Github (en el readme están los enlaces a youtube) con eso deberías tener la base en github para participar aquí.
https://github.com/mouredev/hello-git/tree/2f860b2976eaa4a52b2da333780db26e7e4fc8d7
