### ISSUE TITLE
No se cumplen las reglas de Pull Request

### ISSUE THREAD

**Issue by edalmava** [mouredev/roadmap-retos-programacion#5665]
Estas contribuciones no cumplen las reglas 

Roadmap/07 - RECURSIVIDAD/python/lesterdavid31.py

Roadmap/#00/kotlin/clotracl.kt

Las contribuciones crean directorios que en el caso 1 no corresponde con el tema
Y en el caso 2 ya existe un directorio creado que es 
Roadmap/00 - SINTAXIS, VARIABLES, TIPOS DE DATOS Y HOLA MUNDO/

**Comment by Roswell468** [comment]
Solucionado. Gracias por el aviso! 😃
