### ISSUE TITLE
Hola comunidad 

### ISSUE THREAD

**Issue by Softech2024** [mouredev/roadmap-retos-programacion#6756]
No encuentro la manera de iniciar el proyecto, estoy en la carpeta de Python, descargue el programa, pero no me deja crear un nuevo proyecto, a esto que es la primera vez que uso la plataforma. Como puedo iniciar el proyecto y integrar Python al programa ?

**Comment by h4ckxel** [comment]
Podrías incluir una imagen por favor para poder ayudarte, no puedo entender tu problema.
Instala en las extensiones Python, o el Python Pack, también checa que tengas Python Instalado o puedes descargarlo desde su pagina oficial https://www.python.org/downloads/

**Comment by Jackziel-Sumoza** [comment]
Si el problema es que despues de clonar el repositorio en la carpeta de python no te permite agregar tu Softech2024.py en el directorio, puedes verificar que en el ID que este utilizando o editor de código, no este bloqueado la edición de archivos; podria darse esta situación si no reconoce el autor del proyecto y tu debes manualmente dar los permisos de edición.

Concuerdo con el compañero, podria pasar una captura de pantalla del problema.
