### ISSUE TITLE
Ejercicio 05 - Valor y Referencia sin "ejercicio.md"

### ISSUE THREAD

**Issue by RuhlMirko** [mouredev/roadmap-retos-programacion#6792]
Pense que era un error mio al haber hecho un git pull pero en el repositorio original ya no esta mas.

**Comment by RuhlMirko** [comment]
Adjunto una captura por si acaso:
![screenshot](https://github.com/user-attachments/assets/72ca194c-85b3-48fb-89fd-c83fad2ec7f3)

**Comment by Roswell468** [comment]
Arreglado.
Gracias por avisar!
Saludos!
